import { BiblioCakes } from './cake';
export const CAKES: BiblioCakes[]=[
    {id:1,
    name:" COLETTE",
    description:"Génoise au chocolat, coeur praliné, chantilly à la vanille et praliné coulant .Il fallait une femme pour représenter ce cupcake. Une femme de caractère comme Sidonie-Gabrielle Colette. Aussi légendaire que le praliné maison, elle marque les esprits par sa masculinité, sa sensibilité et son sensuel.Colette nous cristallise avec son caramel et nous charme avec sa croustillance. Auteure comme pâtisserie, impossible de ne pas succomber... ''Le prix de les 5 piéce est 15dt.'' 🧁",
    img:"assets/1.jpg",
    prix:15,
    choix:"sucre"
    },
    {id:2,
    name:"SHAKESPEARE",
    description:"Génoise au chocolat, crème de marron, chantilly au chocolat blanc. Aussi discret et sensible que le célèbre dramaturge anglais. Vous pourrez lui donner une fin tragique en le dévorant ! ''Le prix de les 5 piéce est 20dt.''🧁",
    img:"assets/2.jpg",
    prix:20,
    choix:"sucre"
    },
    {id:3,
    name:"BAUDELAIRE",
    description:"Génoise à la vanille, crème au citron, chantilly à la violette et au citron Charles Baudelaire, âme torturée, écrit dans Les fleurs du mal des poèmes qui évoquent l’enfance mais aussi la mort, qui parlent aussi bien d’art que d’artifice...d’amour comme de prostitution. Les thèmes abordés s’opposent pour créer une ambiance, une humeur, un sentiment unique. L’amertume du citron liée à la douceur de la violette, procurent en bouche la même sensation qu’à la lecture d’un poème de Baudelaire...''Le prix de les 5 piéce est 15dt.''🧁",
    img:"assets/3.jpg",
    prix:15,
    choix:"sucre"
    },
    {id:4,
    name:"MAUPASSANT",
    description:"Génoise à la vanille, crème à la pistache, framboises fraîches, chantilly pistache Guy de Maupassant était réputé pour avoir mauvais caractère. Bien qu’il ait offert à la littérature, des personnages de roman réalistes et attachants.Comme ce cupcake, fait à partir de pâte de pistache maison. Tellement attachant qu’on voudrait l’avoir dans notre estomac pour toujours.''Le prix de les 5 piéce est 20dt.''🧁",     
    img:"assets/4.jpg",
    prix:20,
    choix:"sucre"
    },
    {id:5,
    name:"SAINT-EXUPERY",
    description:"Génoise au chocolat, Kinder Bueno, chantilly au Nutella La leçon principale que nous donne Antoine de Saint-Exupéry à travers Le Petit Prince, est simple : il faut renouer avec son âme d’enfant !  Pour commencer à le faire, choisissez la gourmandise au chocolat qui vous faisait le plus saliver lorsque vous étiez enfant. Vous obtiendrez alors le Saint-Exupéry de vos rêves. Kinder Bueno, Country, Schoko-Bons, Raffaello, KitKat...''Le prix de les 5 piéce est 15dt.''🧁🍫 ",
    img:"assets/5.jpg",
    prix:15,
    choix:"sucre"
    },
    {id:6,
    name:"LAYER CAKE",
    description:"C’est un gâteau à la crème vanille et aux framboises recouvert d’une ganache au chocolat blanc.🎂",
    img:"assets/6.jpg",
    prix:46,
    choix:"sucre"
    },
    {id:7,
    name:"GATEAU AU FRAISE",
    description:"Nos fraisiers fleuris sont généreux 🍓💐. 15 cm de couches onctueuses qui se composent d’une génoise moelleuse imbibée d’un sirop et d’une crème diplomate à la vanille de Madagascar. Nous utilisons pour ces fraisiers nos fraises préférées issues de l’agriculture française : la Gariguette ❤️",
    img:"assets/7.jpg",
    prix:35,
    choix:"sucre"
    },
    {id:8,
    name:"MAGNUM CAKES",
    description:"Rien de plus adorable que des magnum cake pour vos événements. Bibliocakes s’adapte à vos envies pour les customiser.Aussi bien en terme de saveurs que d’esthétisme !''Les 10 sont à 20dt''🍭",
    img:"assets/10.jpg",
    prix:20,
    choix:"sucre"
    },
    {id:9,
    name:"TARTELETTES AU CITRON",
    description:"Une tarte au citron originale, minimaliste et goûteuse comme il faut! La tarte au citron nous l’aimons tous de manières différentes mais la notre met tout le monde d’accord! Une petite portion avec un dosage de meringue parfait 🍋 Vous allez l’adorer…",
    img:"assets/9.jpg",
    prix:15,
    choix:"sucre"
    },
    {id:10,
    name:" MINI BURGER/CLUB THON",
    description:"Nos mini-burgers apéritif qui sont juste un délice, les pains burgers sont briochés et hyper moelleux sont réalisés pour un buffet froid ou un apéritif !!🍔... Le club sandwich, c'est la meilleure goûtée pour tous 🥪",
    img:"assets/13.jpg",
    prix:20,
    choix:"sale"
    },
    {id:11,
    name:"BUGELS AU SAUMON",
    description:"Un délicieux pain , ultra moelleux et grillé, garni de saumon fumé 😋",
    img:"assets/14.jpg",
    prix:25,
    choix:"sale"
    },
    {id:12,
    name:"BATBOUT AU POULET",
    description:"la recette du mini batbout C’est petits pains sont idéales pour faire des mini sandwichs, pour garnir un buffets ou pour un pique-nique.🥙",
    img:"assets/15.jpg",
    prix:18,
    choix:"sale"
    },
    {id:13,
    name:"MINI PIZZA",
    description:"De jolies pizzas faciles et très délicieuses pour vos pique-nique 🍕",     
    img:"assets/16.jpg",
    prix:28,
    choix:"sale"
    },
    {id:14,
    name:"MINI HOT DOG",
    description:"Une recette de mini hot dogs, un format bouchées parfait pour vos occasions 🌭",
    img:"assets/17.jpg",
    prix:30,
    choix:"sale"
    },
     
  ]